[package]
name = "mermaid"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
escape_string = "0.1.2"
headless_chrome = { version = "1.0.15", features = ["fetch"] }
unescape = "0.1.0"
